services:
  grafana-lgtm:
    image: 'grafana/otel-lgtm:latest'
    ports:
      - '3000:3000'
      - '4317'
      - '4318'
  postgres:
    image: 'postgres:18'
    container_name: hr-postgres
    environment:
      - POSTGRES_DB=${SPRING_DATASOURCE_DATABASE_NAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
    ports:
      - '5432'
