spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}?sslmode=${DB_SSL_MODE:require}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 10000

server:
  forward-headers-strategy: framework

management:
  endpoint:
    health:
      probes:
        add-additional-paths: true

  tracing:
    sampling:
      probability: ${TRACING_SAMPLING_PROBABILITY:1.0}
    export:
      otlp:
        enabled: true
  logging:
    export:
      otlp:
        enabled: true

  otlp:
    metrics:
      export:
        enabled: true
        url: ${OTLP_BASE_URL:http://localhost:4318}/v1/metrics
        step: 60s
  opentelemetry:
    resource-attributes:
      deployment.environment.name: ${APP_ENVIRONMENT:dev}
    tracing:
      export:
        otlp:
          endpoint: ${OTLP_BASE_URL:http://localhost:4318}/v1/traces
    logging:
      export:
        otlp:
          endpoint: ${OTLP_BASE_URL:http://localhost:4318}/v1/logs

app:
  init-db: ${INIT_DB:false}