CREATE TABLE departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(50),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    CONSTRAINT uq_departments_name UNIQUE (name)
);

CREATE TABLE employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    hire_date TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    status VARCHAR(255) NOT NULL,
    department_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    -- The unique constraint creates the email index; no duplicate index needed.
    CONSTRAINT idx_employee_email UNIQUE (email),
    CONSTRAINT ck_employees_status CHECK (
        status IN ('ACTIVE', 'ON_LEAVE', 'TERMINATED', 'PROBATION')
    ),
    CONSTRAINT fk_employees_department FOREIGN KEY (department_id)
        REFERENCES departments (id)
);

CREATE INDEX idx_employees_department_id ON employees (department_id);

CREATE TABLE contracts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salary NUMERIC(10, 2) NOT NULL,
    start_date TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    end_date TIMESTAMP(6) WITH TIME ZONE,
    employee_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,

    CONSTRAINT uq_contracts_employee UNIQUE (employee_id),
    CONSTRAINT ck_contracts_salary_positive CHECK (salary > 0),
    CONSTRAINT fk_contracts_employee FOREIGN KEY (employee_id)
        REFERENCES employees (id)
);
